name: Workout Buddy CI  
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        mongodb-version: ['4.2']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: MongoDB installation and setup for Github actions
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm install
      - run: npm run build --prefix frontend
      - run: npm run test
    env:
      CI: true
      MONGO_URI: mongodb://localhost/workoutBuddy
      SECRET: randomtestsecret
      TEST_EMAIL: test@t.com
      TEST_PASSWORD: ABCabc123.

